language: node_js

node_js: node

install:
  - npm install

script:
  - hexo cl
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "HyanCat"
  - git config user.email "hyancat@live.cn"
  - git add .
  - git commit -m "Auto update."
  - git push --force --quiet "https://${GH_TOKEN}@github.com/HyanCat/hyancat.github.io.git" master:master

branches:
  only:
    - master
